apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  token: {{ required "tunnelToken é obrigatório (venha do output do terraform/structurizr)" .Values.tunnelToken | quote }}
